version: 0.0    # CodeDeploy 버전
os: linux
files:
  - source: /  # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 루트로 지정(전체파일)
    destination: /home/dsmd-user/deploy/front/ # source에서 지정된 파일을 받을 위치, 이후 jar를 실행하는 등은 destination에서 옮긴 파일들로 진행
    overwrite: yes

permissions:  # CodeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ec2-user권한을 갖도록 합니다.
  - object: /
    pattern: "**"
    owner: dsmd-user
    group: dsmd-user

hooks:
  AfterInstall:
    - location: deploy.sh
      runas: dsmd-user
